version: '3'

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/17
#    networks:
#      - internal

volumes:
  postgres_data: